version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: c33322-mongo
    ports: 
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  node-dev:
    restart: always
    build: .
    container_name: c3322-node
    depends_on: 
      - mongodb
    ports: 
      - 3000:3000
      - 3001:3001
      - 8000:8000
      - 8080:8080
    volumes:
      - ./applications:/home/c3322
    working_dir: /home/c3322
    entrypoint: "/bin/bash"
    stdin_open: true

